# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c3b678ef319e00e78edffdf28138cb6530459ceaa8b85b3382157299fd62a052f87f1989d6be5e4c3f0720637c3a446c4cb799b264b02845d60bc88d357936de

test:
  secret_key_base: 26eb63f6789a5eeae66733eabb0b09836da6faf937d4f7918c57a5f0e9f909571a5f556f43a28d944a28492436f48dbd939ec6d3f58eeb2f9fd15e4ea3ba54c6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
